### ISSUE TITLE
Clock resets to white colour when time is over

### ISSUE THREAD

**Issue by franziskas** [dtanzer/babystepstimer#1]
Not sure if bug or feature, if the time has expired, the clock turns red, starts counting down from 2:00 again and then it turns white after a couple of seconds (see screenshots).
<img width="189" alt="screen shot 2017-01-19 at 15 55 45" src="https://cloud.githubusercontent.com/assets/5154737/22113950/cd0c6432-de5f-11e6-8680-90144805dbe4.png">

<img width="179" alt="screen shot 2017-01-19 at 15 55 51" src="https://cloud.githubusercontent.com/assets/5154737/22113949/cd057bcc-de5f-11e6-8f29-5aabf1a56195.png">

<img width="174" alt="screen shot 2017-01-19 at 15 55 57" src="https://cloud.githubusercontent.com/assets/5154737/22113948/ccf45ba8-de5f-11e6-8364-b858b5bb8e02.png">

**Comment by dtanzer** [comment]
You never know with legacy code, but you have to preserve the user visible behaviour ;)

(TBH, I designed this as a feature back when I wrote it, because I found it to be annoying if it stays red. But in a real legacy code situation, you probably could not talk to the original developer or business analyst)

**Comment by franziskas** [comment]
@dtanzer I wasn't planning on changing the behaviour, don't worry. This report is outside the exercise, as I want to do a pure refactoring (without behaviour changes) if possible.
